export const MOCK_RESULT = {
  query: "chest pain sometimes, age 55, Nagpur, budget 3 lakhs",
  city: "Nagpur",
  state: "Maharashtra",
  city_tier: 2,
  budget: "Under 3L",
  condition: "Coronary Artery Disease",
  icd10: "I25.1",
  confidence: 72,
  severity: "moderate",
  other_conditions: [
    { name: "Stable Angina Pectoris", icd10: "I20.9", confidence: 18 },
    { name: "Hypertensive Heart Disease", icd10: "I11.9", confidence: 10 },
  ],
  pathway: [
    { step: 1, type: "CONSULTATION", title: "Cardiologist Consultation", desc: "Initial clinical evaluation, history taking, and preliminary cardiac assessment including vitals and auscultation.", covered: true, cost: [0, 0], note: "Bundled in HBP package" },
    { step: 2, type: "INVESTIGATION", title: "ECG + ECHO + Lipid Panel + Blood Tests", desc: "Diagnostic workup: electrocardiogram, echocardiography, lipid profile, CBC, INR, serum creatinine.", covered: true, cost: [3200, 5500] },
    { step: 3, type: "PROCEDURE", title: "Coronary Angiography (CAG)", desc: "Catheter-based imaging of coronary arteries to assess blockage severity and location. Performed under local anaesthesia.", covered: true, cost: [14200, 15000] },
    { step: 4, type: "PROCEDURE", title: "Peripheral Angioplasty (MC017A)", desc: "Balloon inflation and stent placement to restore blood flow through the blocked coronary artery segment.", covered: true, cost: [43200, 49000] },
    { step: 5, type: "STAY", title: "Post-Procedure Hospitalization", desc: "Routine ward recovery with cardiac monitoring, vital tracking, and nursing care. Estimated 3–5 days.", covered: true, cost: [10890, 18150] },
    { step: 6, type: "FOLLOW-UP", title: "Post-Discharge Medications + Review", desc: "15-day bundled medication regimen included in HBP package. Cardiology OPD review at 2–4 weeks post-discharge.", covered: true, cost: [5000, 9000] },
  ],
  cost: {
    procedure: [43200, 49000],
    stay: [10890, 18150],
    medication: [5000, 9000],
    contingency: [5910, 7615],
    total: [65000, 83765],
  },
  assumptions: {
    stacking: "Multi-procedure rule applied: CAG (100%) + Angioplasty (50% of secondary rate)",
    hospital_type: "Government (1.0× multiplier)",
    nabh: "Not accredited (no NABH add-on)",
    los: "3–5 days, Routine Ward",
    meds: "8–12% of procedure base (IRDAI benchmark)",
    contingency: "9% of subtotal",
    bed_rate: "₹2,300/day · Routine Ward (HBP 2022)",
  },
  tier_costs: {
    1: { procedure: [51800, 51800], stay: [13800, 23000], medication: [6200, 11100], contingency: [7200, 9200], total: [79000, 95100] },
    2: { procedure: [43200, 49000], stay: [10890, 18150], medication: [5000, 9000], contingency: [5910, 7615], total: [65000, 83765] },
    3: { procedure: [38500, 43200], stay: [9200, 15300], medication: [4200, 7600], contingency: [4700, 6200], total: [56600, 72300] },
  },
  hospitals: [
    {
      id: 1,
      name: "Wockhardt Heart Hospital",
      type: "mid_private",
      rating_google: 4.2,
      rating_practo: 4.0,
      dist: 3.4,
      beds: 420,
      nabh: true,
      nabh_level: "Entry Level",
      emergency: true,
      discipline: "Allopathic",
      address: "14, Wockhardt Hospital Road, Ramdaspeth, Nagpur, MH 440010",
      phone: "+91-712-6632222",
      specialties: ["Cardiology", "CTVS", "Emergency", "ICU"],
      mult: 1.8,
      range: [117000, 150780],
    },
    {
      id: 2,
      name: "Orange City Hospital & RC",
      type: "mid_private",
      rating_google: 4.4,
      rating_practo: 4.1,
      dist: 6.1,
      beds: 380,
      nabh: false,
      nabh_level: null,
      emergency: true,
      discipline: "Allopathic",
      address: "Wadi, Nagpur, Maharashtra 440023",
      phone: "+91-712-2730000",
      specialties: ["Cardiology", "Orthopedics", "Neurology", "Oncology"],
      mult: 2.0,
      range: [130000, 167530],
    },
    {
      id: 3,
      name: "Govt. Medical College Hospital",
      type: "government",
      rating_google: 3.8,
      rating_practo: 3.6,
      dist: 8.2,
      beds: 800,
      nabh: false,
      nabh_level: null,
      emergency: true,
      discipline: "Allopathic",
      address: "Medical Square, Nagpur, Maharashtra 440003",
      phone: "+91-712-2748888",
      specialties: ["Cardiology", "General Medicine", "Surgery", "Paediatrics", "Ortho"],
      mult: 1.0,
      range: [65000, 83765],
    },
  ],
}

export const EXAMPLES = [
  // Short
  "Knee pain, Mumbai",
  "Chest pain, age 55, Delhi",
  "Eye cataract surgery, Pune",
  "Back surgery, Hyderabad",
  "Kidney stone, Bhopal",
  "Fever for 3 days, Lucknow",
  // Medium
  "Appendix removal, Jaipur, budget 1.5L",
  "Gallbladder stone removal, Chennai, age 40, budget 2L",
  "Knee replacement, Nagpur, budget 3 lakhs",
  "Heart bypass surgery, Mumbai, budget 8 lakhs",
  "Stroke recovery, age 68, Kolkata",
  "Hip fracture surgery, age 75, Bengaluru",
  "Diabetes complications, Lucknow, age 65",
  "Brain tumor treatment, age 40, Hyderabad, budget 10L",
  // Detailed
  "Chest pain radiating to left arm, age 58, diabetic, Mumbai, budget 5 lakhs",
  "Severe knee pain for 6 months, can't walk properly, age 62, Nagpur, budget 2.5 lakhs",
  "Recurring kidney stones with severe pain, right side, age 35, Bhopal, budget 1.5L",
  "High BP and chest tightness on exertion, age 55, non-smoker, Hyderabad, budget 4L",
  "Diabetic foot ulcer not healing for 2 months, age 60, Lucknow, budget 80K",
  "Knee pain and internal bleeding after fall, age 45, Mumbai, budget 10 lakhs",
]

export const STATS = [
  { value: "30,273", label: "Hospitals" },
  { value: "1,670", label: "HBP Procedures" },
  { value: "87", label: "Specialties" },
  { value: "3-Tier", label: "Cost Model" },
]
